# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 729398de6cb818ac1689dc889aa50cb425fde341adbee4f334ad3ed47dd6418597c4d81752d2f9708822684f2fd9c7f3b9ab00448f95eb97274132ba8ee13a8b

test:
  secret_key_base: e569e0f40a74637b5937b0d12ad44c357e2a61350319cfb3254b1249b903b0239ddbc674ff04c637ef510e6c1fee484b13db6cb1cea1936fb4f8a1e9b875ce13

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
